spring.application.name=srsbackend
spring.datasource.url=jdbc:postgresql://localhost:5432/srs_database
spring.datasource.username=srs_user
spring.datasource.password=srs_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true